'use strict';
// tests for create
// Generated by serverless-mocha-plugin

const mod         = require('../restApi/multi/create/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

describe('create', () => {
  before(function (done) {
    wrapper.init(mod);

    done()
  })

  it('error is null and response has message property', (done) => {
    wrapper.init(mod);
    wrapper.run({}, (err, response) => {
      expect(err).to.be.null;
      expect(response).to.be.property('message');
      done();
    });
  });
});
