'use strict';
// tests for show
// Generated by serverless-mocha-plugin

const mod         = require('../restApi/multi/show/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

describe('show', function() {
  before(function (done) {
    wrapper.init(mod);

    done()
  })

  it('error is null and response is not null', function(done) {
    wrapper.init(mod);
    wrapper.run({}, function(err, response) {
      expect(err).to.be.null;
      expect(response).not.to.be.null;
      expect(response).to.have.property('message').and.not.null;
      done();
    });
  });

  it('parameter should be undefined', function(done) {
    wrapper.init(mod);
    wrapper.run({}, function(err, response) {
      expect(response.event.pathId).to.be.undefined;
      done();
    });
  });
});
