'use strict';
// tests for single
// Generated by serverless-mocha-plugin

const mod         = require('../restApi/single/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const wrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

describe('single', () => {
  before(function (done) {
    wrapper.init(mod);

    done()
  })

  it('response err to be null and message property included', (done) => {
    wrapper.init(mod);
    wrapper.run({}, (err, response) => {
      expect(err).to.be.null;
      expect(response).to.have.property('message').and.not.null;
      done();
    });
  });
});
